### ISSUE TITLE
Add support for node 16 to build

### ISSUE THREAD

**Issue by creisle** [bcgsc/pori_graphkb_client#20]
- [ ] Update the build workflow to use a matrix and test on node versions: 12, 14, and 16
- [ ] Update the docker container to default to node 16
- [ ] test running the node-16 docker container with the orientdb and graphkb client containers

**Comment by creisle** [comment]
@elewis2 It occurs to me that for the client we probably only need 1 version of node supported since we transpile the whole thing when it is actually used anyway so it is probably a waste of build minutes to have more than one. How do you feel about just fixing it to use node-16 and ditching 12/14?

**Comment by areisle** [comment]
I tried swapping to node16, but it seems there's dependencies with conflicting dependencies of react versions, the version of aggrid being used requires < react@17, and @testing-library/react-hooks requires >= react@17. so I think this will depend on first updating aggrid and react
