### ISSUE TITLE
AuthenticationError: no user found for the username 'iprdemo'

### ISSUE THREAD

**Issue by alirizaaribas-ibg** [bcgsc/pori_graphkb_client#53]
**Describe the bug**
When I tried to access the graphkb client at localhost:5000, it recognizes the session but gives errors. Repeatedly redirects between error/login pages as I understand from console logs.

**To Reproduce**
Steps to reproduce the behaviour: The scripts I followed 
[docker-run.txt](https://github.com/bcgsc/pori_graphkb_client/files/8481849/docker-run.txt)

1. Logout
2. Then tried to login
3. Sometimes objects are coming, but not staying alive. after a few seconds, all page redirects to an error page.(screenshots attached below)
4. Gives errors on developer console

**Expected behaviour**
Sorry, I don't know what to expect. My manager gave me [your guide to install](https://bcgsc.github.io/pori/) and make it running. So, If there a workflow description as demo, I will follow the steps.

**Versions (please complete the following information):**

- OS: Ubuntu 20.04
- NodeJS: 16
- Version: dev and prod from github
- OrientDB Version: How can I check it?(Is it enough of docker images are running well? screenshot added below)

**Additional context**
Screenshots and logs here:
console log(copied as text) 
[error_browser01.txt](https://github.com/bcgsc/pori_graphkb_client/files/8481814/error_browser01.txt)

browser console 
![error_browser01](https://user-images.githubusercontent.com/55430656/163190925-ce62271a-fe61-4bb2-b077-d6617cc1eefd.png)

![error_grapkb01](https://user-images.githubusercontent.com/55430656/163190932-e1d5d491-98b2-4d1f-94b0-c4c75126dfa1.png)
![error_grapkb02](https://user-images.githubusercontent.com/55430656/163190934-7e86b5a7-fb91-4129-9b1b-3eb6aab5ff09.png)
![error_grapkb03](https://user-images.githubusercontent.com/55430656/163190936-6458c4bf-0d7a-4b29-aad7-ac56ca0eaa28.png)
![error_grapkb04](https://user-images.githubusercontent.com/55430656/163190941-740e0764-a3ce-40a0-9b53-7093181e3554.png)
![error_grapkb05](https://user-images.githubusercontent.com/55430656/163190945-980784c6-8a41-41c8-98d7-2af50c2fc4c5.png)

docker is running well:
![noerror_docker](https://user-images.githubusercontent.com/55430656/163191587-54479032-fa2a-49e1-a764-07b69f0bb3e9.png)

iprdemo page is running well:
![noerror_iprdemo](https://user-images.githubusercontent.com/55430656/163191649-a8535738-df55-4dfe-8b11-eda3fef8ca75.png)

How can I make it all running? Thanks.

**Comment by creisle** [comment]
@alirizaaribas-ibg We saw similar behaviour in our development deployment which we have since fixed. We suspect it is related to an update of an external package. I have set up a release for this fix which should be released in the next couple of days. https://github.com/bcgsc/pori_graphkb_client/pull/54. You can build the client docker container from this branch now if you'd like to test it out now

**Comment by alirizaaribas-ibg** [comment]
@creisle  Except ipr upload, all is working now. Thank you.

**Comment by creisle** [comment]
> @creisle Except ipr upload, all is working now. Thank you.

Great! Do you have a ticket for the issue you encountered with ipr upload already? If so I will close this one and help you debug upload there
